{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "axosyslog.serviceAccountName" . }}
  namespace: {{ include "axosyslog.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "axosyslog.serviceAccountName" . }}
    namespace: {{ include "axosyslog.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "axosyslog.serviceAccountName" . }}
{{- end -}}
